name: "Assign Reviewers"
on:  
  pull_request:
    types: [opened, ready_for_review]
     
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v0.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: ""     # only works for GitHub Organisation/Teams
        persons: "knewzen"          # add individual persons here 
        include-draft: false        # Draft PRs will be skipped by default, enable if you need it 
