name: "Assign Reviewers"
on:  
  pull_request:
    types: [opened, ready_for_review]
     
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: sinchang-bot/auto-assign-review-teams@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: ""     # only works for GitHub Organisation/Teams
        persons: "knewzen"          # add individual persons here
