name: "Assign Reviewers"
on:  
  push:
  pull_request:
    types: [opened, ready_for_review]
     
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v0.0.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "no-team"     # only works for GitHub Organisation/Teams
        persons: "knewzen"          # add individual persons here
